import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import DefaultLayout from "../Layouts/defaultLayout";

interface IState {
  name: string;
  description: string;
  email: string;
  image: { url: string; alt: string };
}

const Cat = () => {
  const [cat, setCat] = useState<IState | null>();
  const router = useRouter();
  const { id } = router.query;

  const fetchCat = async () => {
    const response = await fetch(`/api/cats/${id}`);
    const data = await response.json();
    console.log(data.cat[0]);

    setCat(data.cat[0]);
  };

  useEffect(() => {
    fetchCat();
  }, []);

  return (
    <DefaultLayout>
      <div className={styles.cat}>
        {cat && (
          <>
            <Head>
              <title>Hi ! I'm {cat.name}</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
              <img
                src={cat.image.url}
                alt={cat.image.alt}
                style={{ height: "500px" }}
              />
            </div>
            <div style={{ marginLeft: "1em" }}>
              <h3>{cat.name}</h3>
              <p style={{ width: "550px" }}>{cat.description}</p>
              <p>Contact: {cat.email}</p>
              <button
                type="button"
                className="btn btn-secondary"
                onClick={() => router.back()}
              >
                Back to cats
              </button>
            </div>
          </>
        )}
      </div>
    </DefaultLayout>
  );
};

export default Cat;
