import React, { useEffect, useState } from "react";
import { useQuery } from "@apollo/client";
import Head from "next/head";
import Card from "../../components/card/card";
import { GET_RESTAURANTS } from "../api/restaurants";
import DefaultLayout from "../Layouts/defaultLayout";
import styles from "../../styles/Home.module.css";

interface IData {
  id: string;
  attributes: {
    name: string;
    email: string;
    phone: string;
    images: {
      data: [
        {
          attributes: {
            url: string;
          };
        }
      ];
    };
  };
}

const Restaurants = () => {
  const { loading, error, data } = useQuery(GET_RESTAURANTS);
  console.log(loading, error, data);

  return (
    <DefaultLayout>
      <Head>
        <title>Restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["cat-card-container"]}>
        {data &&
          data.restaurants.data.map(
            ({ id, attributes }: IData, index: number) => (
              <Card
                key={id}
                id={id}
                name={attributes.name}
                phone={attributes.phone}
                email={attributes.email}
                image={{
                  url: attributes.images.data[index].attributes.url,
                  alt: attributes.name,
                }}
              />
            )
          )}
      </div>
    </DefaultLayout>
  );
};

export default Restaurants;
