import React, { useEffect, useState } from "react";
import { useQuery } from "@apollo/client";
import Head from "next/head";
import Card from "../../components/card/card";
import { GET_RESTAURANTS } from "../api/restaurants";
import DefaultLayout from "../Layouts/defaultLayout";
import styles from "../../styles/Home.module.css";

const Cats = () => {
  const [cats, setCats] = useState([]);

  const { loading, error, data } = useQuery(GET_RESTAURANTS);
  console.log(loading, error, data);

  const fetchCats = async () => {
    const response = await fetch("/api/cats");
    const data = await response.json();
    console.log(data);
    setCats(data);
  };

  useEffect(() => {
    fetchCats();
  }, []);

  return (
    <DefaultLayout>
      <Head>
        <title>Our cats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["cat-card-container"]}>
        {cats.map(({ name, phone, email, image, id }) => (
          <Card
            key={id}
            name={name}
            phone={phone}
            email={email}
            image={image}
            id={id}
          />
        ))}
      </div>
    </DefaultLayout>
  );
};

export default Cats;
