import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { IRestaurantData } from "../../interfaces/pages/restaurants/restaurant";
import styles from "../../styles/Home.module.css";
import { useRestaurant } from "../api/restaurants/[id]";
import DefaultLayout from "../Layouts/defaultLayout";

const Restaurant = () => {
  const router = useRouter();
  const id = router.query.id;
  const URL = process.env.NEXT_PUBLIC_API_URL;

  let response: IRestaurantData = {
    loading: true,
    error: null,
    data: null,
  };

  let data = {
    email: "",
    name: "",
    description: "",
    images: {
      data: [
        {
          attributes: {
            url: "",
          },
        },
      ],
    },
  };

  // if (id && typeof id === "string") {
  response = useRestaurant(id);
  // console.log("Res", response);

  if (response.data) {
    data = response.data.restaurant.data.attributes;
  }
  // }
  console.log("ENV: ", process.env.NEXT_PUBLIC_API_URL);

  return (
    <DefaultLayout>
      <div className={styles.cat}>
        {response.data && (
          <>
            <Head>
              <title>Hi ! I am {data.name}</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
              <img
                src={`${URL}${data.images.data[0].attributes.url}`}
                alt={data.name}
                style={{ height: "500px" }}
              />
            </div>
            <div style={{ marginLeft: "1em" }}>
              <h3>{data.name}</h3>
              <p style={{ width: "550px" }}>{data.description}</p>
              <p>Contact: {data.email}</p>
              <button
                type="button"
                className="btn btn-secondary"
                onClick={() => router.back()}
              >
                Back to cats
              </button>
            </div>
          </>
        )}
      </div>
    </DefaultLayout>
  );
};

export default Restaurant;
