import React from "react";
import Head from "next/head";
import Card from "../../components/card/card";
import { useRestaurants } from "../api/restaurants";
import DefaultLayout from "../Layouts/defaultLayout";
import styles from "../../styles/Home.module.css";
import { IRestaurantsData } from "../../interfaces/pages/restaurants";

const Restaurants = () => {
  const { loading, error, data } = useRestaurants();

  return (
    <DefaultLayout>
      <Head>
        <title>Restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["cat-card-container"]}>
        {data &&
          data.restaurants.data.map(
            ({ id, attributes }: IRestaurantsData, index: number) => (
              <Card
                key={id}
                id={id}
                name={attributes.name}
                phone={attributes.phone}
                email={attributes.email}
                image={{
                  url: attributes.images.data[0].attributes.url,
                  alt: attributes.name,
                }}
              />
            )
          )}
      </div>
    </DefaultLayout>
  );
};

export default Restaurants;
